name: CI Workflow

# どのタイミングで実行するか（ここではメインブランチへのプッシュ時）
on:
  push:
    branches: [ "feature/try" ]
  pull_request:
  
jobs:
  test:
    # 実行するOS環境
    runs-on: ubuntu-latest

    steps:
      - name: 該当ブランチ
        run : echo "PR出した側"
        run: echo "This is the feature/try branch"