name: CI Workflow

# どのタイミングで実行するか（ここではメインブランチへのプッシュ時）
on:
  push:
    branches: [ "feature/try-github-actions" ]
  pull_request:
    branches: [ "feature/try-github-actions" ]

jobs:
  test:
    # 実行するOS環境
    runs-on: ubuntu-latest

    steps:
      - name: 該当ブランチ
        run: echo "This is the feature/try-github-actions branch"